/* ============================================================================
   build-geo.cjs — turns the GeoNames India dump into the site's gazetteer.

   Produces two tiers:
     site/assets/js/geo-top.js   inline, instant: every place of real size
     site/geo/<prefix>.txt       lazy shards covering all 557k+ populated places
     site/geo/manifest.txt       which shard prefixes exist

   Usage:  node tools/build-geo.cjs <path-to-IN.txt> <admin1CodesASCII.txt> <admin2Codes.txt>
============================================================================ */
'use strict';
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const [, , IN_TXT, ADMIN1, ADMIN2] = process.argv;
if (!IN_TXT || !ADMIN1 || !ADMIN2) {
  console.error('usage: node tools/build-geo.cjs IN.txt admin1CodesASCII.txt admin2Codes.txt');
  process.exit(1);
}

const OUT_JS = path.join(__dirname, '..', 'site', 'assets', 'js', 'geo-top.js');
const OUT_DIR = path.join(__dirname, '..', 'site', 'geo');
const SHARD_MAX = 2500;      // split a prefix further once it exceeds this
const TOP_MIN_POP = 5000;    // inline tier: places at least this big
const TOP_CAP = 2600;        // hard cap on the inline tier

/* ---------- admin lookups ------------------------------------------------ */

function readAdmin(file, keep) {
  const map = new Map();
  for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
    if (!line.startsWith('IN.')) continue;
    const f = line.split('\t');
    map.set(f[0], keep(f));
  }
  return map;
}
const A1 = readAdmin(ADMIN1, f => f[2] || f[1]);   // "IN.16" -> "Maharashtra"
const A2 = readAdmin(ADMIN2, f => f[2] || f[1]);   // "IN.16.xxx" -> district

// stable index arrays so shards can store small integers
const states = [], stateIdx = new Map();
const dists = [], distIdx = new Map();
function idxOf(arr, map, name) {
  if (!name) return -1;
  if (map.has(name)) return map.get(name);
  const i = arr.length; arr.push(name); map.set(name, i); return i;
}
// seed states in a fixed order
[...A1.values()].sort().forEach(s => idxOf(states, stateIdx, s));

/* ---------- pass 1: read and normalise ----------------------------------- */

function norm(s) {
  return s.toLowerCase()
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '');
}

const rows = [];
const seen = new Set();

(async function main() {
  const rl = readline.createInterface({
    input: fs.createReadStream(IN_TXT, { encoding: 'utf8' }),
    crlfDelay: Infinity
  });

  let total = 0;
  for await (const line of rl) {
    const f = line.split('\t');
    if (f[6] !== 'P') continue;                 // populated places only
    const name = (f[2] || f[1] || '').trim();   // asciiname preferred
    if (!name) continue;
    const lat = parseFloat(f[4]), lon = parseFloat(f[5]);
    if (!isFinite(lat) || !isFinite(lon)) continue;

    const st = A1.get('IN.' + f[10]) || '';
    const dt = A2.get('IN.' + f[10] + '.' + f[11]) || '';
    const pop = parseInt(f[14], 10) || 0;

    // drop near-duplicates: same name, same district, within ~1 km
    const key = norm(name) + '|' + f[10] + '|' + f[11] + '|' +
                lat.toFixed(2) + '|' + lon.toFixed(2);
    if (seen.has(key)) continue;
    seen.add(key);

    rows.push({
      n: name,
      s: idxOf(states, stateIdx, st),
      d: idxOf(dists, distIdx, dt),
      la: Math.round(lat * 10000),
      lo: Math.round(lon * 10000),
      p: pop,
      k: norm(name)
    });
    total++;
  }
  console.log('populated places kept:', total, '(deduped from 557,995)');
  build();
})();

/* ---------- pass 2: emit ------------------------------------------------- */

function build() {
  // ---------- inline tier ----------
  const top = rows.filter(r => r.p >= TOP_MIN_POP)
                  .sort((a, b) => b.p - a.p)
                  .slice(0, TOP_CAP)
                  .sort((a, b) => a.n.localeCompare(b.n));

  const js = [];
  js.push('/* geo-top.js — generated by tools/build-geo.cjs. Do not edit by hand.');
  js.push('   The inline tier: every Indian place of population >= ' + TOP_MIN_POP + ',');
  js.push('   searchable with zero network. The full 557k-place gazetteer lives in');
  js.push('   site/geo/ and is fetched on demand. */');
  js.push('(function (root) {');
  js.push('  var STATES = ' + JSON.stringify(states) + ';');
  js.push('  var DISTS = ' + JSON.stringify(dists) + ';');
  js.push('  // name \\t stateIdx \\t distIdx \\t lat*1e4 \\t lon*1e4 \\t population');
  js.push('  var TOP = ' + JSON.stringify(
    top.map(r => [r.n, r.s, r.d, r.la, r.lo, r.p].join('\t')).join('\n')
  ) + ';');
  js.push('  root.GeoIN = { STATES: STATES, DISTS: DISTS, TOP: TOP };');
  js.push('})(window);');
  fs.writeFileSync(OUT_JS, js.join('\n') + '\n');
  console.log('inline tier:', top.length, 'places ->',
              (fs.statSync(OUT_JS).size / 1024).toFixed(0) + ' KB');

  // ---------- sharded tier ----------
  fs.rmSync(OUT_DIR, { recursive: true, force: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });

  // group adaptively: start at 3 chars, deepen while a bucket is too big
  const buckets = new Map();
  for (const r of rows) {
    const key = (r.k + '___').slice(0, 3);
    if (!buckets.has(key)) buckets.set(key, []);
    buckets.get(key).push(r);
  }
  let queue = [...buckets.entries()];
  const final = [];
  while (queue.length) {
    const [pfx, list] = queue.pop();
    if (list.length <= SHARD_MAX || pfx.length >= 6) { final.push([pfx, list]); continue; }
    const sub = new Map();
    for (const r of list) {
      const key = (r.k + '______').slice(0, pfx.length + 1);
      if (!sub.has(key)) sub.set(key, []);
      sub.get(key).push(r);
    }
    // a deeper split that does not actually split is pointless
    if (sub.size === 1) { final.push([pfx, list]); continue; }
    queue = queue.concat([...sub.entries()]);
  }

  /* Every shard filename is prefixed with "s". Without it, prefixes like
     "con", "prn", "aux" and "nul" collide with Windows reserved device names:
     the file cannot be created properly and git refuses to index it. */
  let bytes = 0, biggest = 0, biggestName = '';
  for (const [pfx, list] of final) {
    list.sort((a, b) => b.p - a.p || a.n.localeCompare(b.n));
    const body = list.map(r => [r.n, r.s, r.d, r.la, r.lo, r.p].join('\t')).join('\n');
    fs.writeFileSync(path.join(OUT_DIR, 's' + pfx + '.txt'), body);
    bytes += body.length;
    if (list.length > biggest) { biggest = list.length; biggestName = pfx; }
  }

  // prefixes only: states and districts already ship inside geo-top.js
  fs.writeFileSync(path.join(OUT_DIR, 'manifest.txt'),
    final.map(f => f[0]).sort().join('\n'));

  console.log('shards:', final.length,
              '| total', (bytes / 1048576).toFixed(1) + ' MB raw',
              '| largest', biggestName, biggest, 'entries',
              '| manifest', (fs.statSync(path.join(OUT_DIR, 'manifest.txt')).size / 1024).toFixed(0) + ' KB');
}
